### ISSUE TITLE
Incorporacion RNC con Aumento de Datos y Dropout

### ISSUE THREAD

**Issue by felixNilo** [ringa-tech/exportacion-numeros#1]
Hola Ringa.
He estado tratando de incorporar los tres modelos en un sola vista de manera de compara en linea las predicciones de los modelos, pero llegue a la problematica al importar el modelo de RNC con Aumento de Datos y Dropout mediante JS. El error que obtengo es el siguiente:

**Error: Based on the provided shape, [1600,100], the tensor should have 160000 values but has 145034**

Me parece que es por el arreglo que le estoy entregando al modelo que es el mismo arreglo que le entrego a la red densa tal como tu lo planteas.

Saludos.

**Comment by rmontemayor-borregosolar** [comment]
Hola, en teoría no debería ser inconveniente siempre y cuando todos los modelos que vas a probar reciban tensores con las mismas formas. Entiendo en tu caso tienes uno de [1600,100], y por algún motivo se le están enviando menos? Imaginaría que es en la entrada, algo en la variable con la que generas el tensor (o que el modelo tenga una forma diferente de entrada).

Si te sirve revisa este ejemplo, aquí tengo varios modelos trabajando con una misma entrada, dime como lo ves (creo que este no lo tengo en github pero puedes ver el código):
https://ringa-tech.com/cnn/numeros/

**Comment by ringa-tech** [comment]
Hola, en teoría no debería ser inconveniente. Con el error que pone es un problema con las formas de los tensores, que puede ser que la variable no tenga la forma esperada (1600x100) o que ese modelo específico espera otra forma en la entrada.

Revisa por favor esta página, aquí hago lo que intentas hacer, no lo tengo en Github creo pero puedes ahí ver el código, dime cómo lo ves y si te sirve para solucionar tu problema:

https://ringa-tech.com/cnn/numeros/

**Comment by felixNilo** [comment]
Descargué tu json del modelo 3 para cargarlo de forma local, pero aún así me arroja errores al momento de cargar el modelo.

**Comment by ringa-tech** [comment]
¿Ok, la verdad podrían ser muchas cosas, tendrás un repositorio o fork donde puedas poner tu archivo para revisarlo? O si no, al menos de este último que dices (cargar el json) pásame el error específico. Solo como recordatorio, debes descargar el json y los archivos "bin", y al menos de manera local, indicas solo el json, y debe ser sobre un servidor http para poder cargarlo.

**Comment by felixNilo** [comment]
Solucionado!
El problema era justamente el archivo .bin
No lo había cargado correctamente.
Gracias Ringa!
